### ISSUE TITLE
Printed Part Insert Size?

### ISSUE THREAD

**Issue by Morfesto** [Vitalii3D-xyz/MetalTap#2]
Hello, I printed the following parts but the holes where the threaded inserts go in appear to be too small.

Opto Tap Adapter.stl
Carriege Front Magnet Holder.stl
Carriege Center Magnet Holder.stl

Is it supposed to be something other than an M3 threaded inserts?

**Comment by Vitalii3D-xyz** [comment]
I use default heat inserts from Voron BOM. They are little bit tight fit, but feel free to increase size in CAD file. 
When bought from my shop you receive all printed parts preassembled, so you may want to leave feedback for shop where you got your aluminium part :)

![IMG_3524](https://github.com/Vitalii3D-xyz/MetalTap/assets/131134819/07761e06-d88b-4ed0-b32a-5c46885cf33d)

**Comment by Morfesto** [comment]
I'm using the same inserts, and all my other holes line up perfect, odd.

Edit, upon further inspection it might be a tiny bit of elephant's foot making the holes super tight.

**Comment by Vitalii3D-xyz** [comment]
Closing
