### ISSUE TITLE
Carriage front magnet holders

### ISSUE THREAD

**Issue by Pyromuffin** [Vitalii3D-xyz/MetalTap#5]
Hi, the voron tap R8 errata suggests that it's possible to use magnets on the carriage front as well as on the carriage center. It looks like magnets won't fit in the printed screw holders in this design. Would it be possible to add a version that can hold magnets? Or have you tested this and found that it doesn't work for some reason?

Thanks!

**Comment by Vitalii3D-xyz** [comment]
Hello @Pyromuffin, as I understand you are trying to run 4 magnets version. I will bring back that option soon, but with rigidity of aluminium 4 magnets version has very strong force and can scratch build plate. I will try to get it ready today

**Comment by kyleisah** [comment]
@Vitalii3D-xyz just now seeing I must have accidentally removed the magnet parts when I did the CAD updates. Sorry about that!

**Comment by Vitalii3D-xyz** [comment]
4 magnets version is back! Closing this issue
