### ISSUE TITLE
Not an issue but not sure how to contact you...

### ISSUE THREAD

**Issue by yonkiman** [Vitalii3D-xyz/MetalTap#8]
(Sorry, I'm not very good with github...)

I modified your Wired Optical Sensor Mount.stl to support [these sensors](https://www.amazon.com/gp/product/B07MFT8NWJ).  I put it on Printables (with the f3d file) [here](https://www.printables.com/model/803495-modified-opto-mount-for-vitalii-tap).

You can add it to your repo if you'd like, you can tell me to take it down, whatever.  Just wanted to let you know.

And also want to let you know that I really like your TAP - I've bought two of them and they're working much better than my plastic ones ever did.

Fred (fred@yonkitime.com)

**Comment by Vitalii3D-xyz** [comment]
Thank you Fred! It is amazing addition! 
I have added link to your model in README

**Comment by yonkiman** [comment]
Happy to contribute!  Feel free to add it to your repository if you want.
